# Generated by Django 5.2.5 on 2025-08-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
