# Generated by Django 5.2.5 on 2025-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_compras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdidas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
